jobs:
- job: Release_PhpRuntimeBaseImage
  displayName: Push PHP Runtime Base Image to MCR
  timeoutInMinutes: 250
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'php'

- job: Release_PhpFpmNginxRuntimeBaseImage
  displayName: Push PHP-FPM Runtime Base Image to MCR
  timeoutInMinutes: 250
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'php-fpm'

- job: Release_DotNetCoreRuntimeBaseImage
  displayName: Push DotNetCore Runtime Base Images to MCR
  timeoutInMinutes: 250
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'dotnetcore'

- job: Release_NodeBaseImage
  displayName: Push Node Base Image to MCR
  timeoutInMinutes: 300
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'node'

- job: Release_RubyBaseImage
  displayName: Push Ruby Base Image to MCR
  timeoutInMinutes: 300
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      aseImageName: 'ruby'

- job: Release_YarnCacheBuildBaseImage
  displayName: Push Yarn Cache Build Base Image to MCR
  timeoutInMinutes: 250
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: _releaseBaseImagesStepTemplate.yml
    parameters:
      baseImageName: 'yarn-cache-build'