variables:
    ascName: oryxSP
    acrName: oryxdevmcr.azurecr.io
    skipComponentGovernanceDetection: true
  
jobs:
- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build Yarn cache image for stretch
    scriptPath: ./build/buildBuildImageBases.sh
    imageDir: yarn-cache
    imageDebianFlavor: stretch
    artifactsFileName: yarn-cache-buildimage-bases-stretch.txt
    jobName: Build_YarnCache_BaseImage_Stretch

- job: Release_YarnCacheBaseImage
  dependsOn: 
    - Build_YarnCache_BaseImage_Stretch
  displayName: Push image to MCR
  timeoutInMinutes: 250
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: ../templates/_releaseBaseImagesStepTemplate.yml
      parameters:
        baseImageName: 'yarn-cache-build'
